##Конфигурация плагина
tag: '&8(&cDC&8) '
lang: ru_RU
log: true
save-interval: 300
save-log: true
send-player-messages: false
## Защитный модуль
protections:
  container: true #Байпсс : draimcreative.container
  spawn_egg: true #Байпсс : draimcreative.spawner
  drop: true #Байпсс : draimcreative.drop
  pickup: true #Байпсс : draimcreative.pickup
  build: false #Байпсс : draimcreative.build
  entity: true #Байпсс : draimcreative.entity
  pvp: true #Байпсс : draimcreative.hit.player
  pve: true #Байпсс : draimcreative.hit.monster
  lore: false #Байпсс : draimcreative.bypass.lore
  loot: true
  spawn-build: true
  throw: true
  commands: true
## Разновидности инветарей
inventory:
  adventure: false #Байпсс : draimc.bypass.inventory
  creative: true #Байпсс : draimc.bypass.inventory
## Черный список предеметов
blacklist:
  place: #Байпсс : draimcreative.bypass.blacklist.place
    - 'ARMOR_STAND'
    - 'ANVIL'
    - 'CHIPPED_ANVIL'
    - 'DAMAGED_ANVIL'
    - 'BEDROCK'
    - 'END_PORTAL_FRAME'
    - 'TNT'
    - 'SCAFFOLDING'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - 'BEACON'
    - 'GRASS_PATH'
    - 'END_PORTAL'
    - 'BARRIER'
    - 'WITHER_SKELETON_SKULL'
    - 'END_CRYSTAL'
    - 'POLISHED_BLACKSTONE_PRESSURE_PLATE'
    - 'CRIMSON_BUTTON'
    - 'ACACIA_PRESSURE_PLATE'
    - 'WARPED_PRESSURE_PLATE'
    - 'CRIMSON_PRESSURE_PLATE'
    - 'DARK_OAK_PRESSURE_PLATE'
    - 'OAK_PRESSURE_PLATE'
    - 'STONE_PRESSURE_PLATE'
    - 'BIRCH_PRESSURE_PLATE'
    - 'SPRUCE_PRESSURE_PLATE'
    - 'LEVER'
    - 'STONE_BUTTON'
    - 'OAK_BUTTON'
    - 'POLISHED_BLACKSTONE_BUTTON'
    - 'BIRCH_BUTTON'
    - 'JUNGLE_BUTTON'
    - 'ACACIA_BUTTON'
    - 'DARK_OAK_BUTTON'
    - 'WARPED_BUTTON'
    - 'CHEST'
    - 'DISPENSER'
    - 'DROPPER'
    - 'TRAPPED_CHEST'
    - 'FURNACE'
    - 'HOPPER'
    - 'BARREL'
    - 'BLAST_FURNACE'
    - 'SMOKER'
  use: #Байпсс : draimcreative.bypass.blacklist.use
    - 'CRIMSON_BUTTON'
    - 'POLISHED_BLACKSTONE_PRESSURE_PLATE'
    - 'SHULKER_BOX'
    - 'WHITE_SHULKER_BOX'
    - 'ORANGE_SHULKER_BOX'
    - 'MAGENTA_SHULKER_BOX'
    - 'LIGHT_BLUE_SHULKER_BOX'
    - 'YELLOW_SHULKER_BOX'
    - 'LIME_SHULKER_BOX'
    - 'PINK_SHULKER_BOX'
    - 'GRAY_SHULKER_BOX'
    - 'LIGHT_GRAY_SHULKER_BOX'
    - 'CYAN_SHULKER_BOX'
    - 'PURPLE_SHULKER_BOX'
    - 'BLUE_SHULKER_BOX'
    - 'BROWN_SHULKER_BOX'
    - 'GREEN_SHULKER_BOX'
    - 'RED_SHULKER_BOX'
    - 'BLACK_SHULKER_BOX'
    - 'ANVIL'
    - 'CHIPPED_ANVIL'
    - 'DAMAGED_ANVIL'
    - 'BEACON'
    - 'ARMOR_STAND'
    - 'SPLASH_POTION'
    - 'LINGERING_POTION'
    - 'FLINT_AND_STEEL'
    - 'FIRE_CHARGE'
    - 'EXPERIENCE_BOTTLE'
    - 'ENDER_EYE'
    - 'EGG'
    - 'BONE_MEAL'
    - 'LAVA_BUCKET'
    - 'SHEARS'
    - 'GRASS_PATH'
    - 'JUKEBOX'
    - 'FLOWER_POT'
    - 'ACACIA_SIGN'
    - 'BIRCH_SIGN'
    - 'DARK_OAK_SIGN'
    - 'JUNGLE_SIGN'
    - 'OAK_SIGN'
    - 'SPRUCE_SIGN'
    - 'ACACIA_WALL_SIGN'
    - 'BIRCH_WALL_SIGN'
    - 'DARK_OAK_WALL_SIGN'
    - 'JUNGLE_WALL_SIGN'
    - 'OAK_WALL_SIGN'
    - 'SPRUCE_WALL_SIGN'
  get: #Байпсс : draimcreative.bypass.blacklist.get
    - 'diamond'
  break:
    - 'BEDROCK'
    - 'END_PORTAL_FRAME'
  commands:
    - 'ah'
    - 'auc'
    - 'buy'
    - 'sell'
    - 'chest'
    - 'gift'
    - 'bid'
    - 'invsee'
## Lore settings
creative-lore:
  - '&6Предмет {ITEM}'
  - '&7Создан игром {PLAYER}'
  - '&7{UUID}'